### ISSUE TITLE
NM - Megalobugard - Missing auto-regen trait

### ISSUE THREAD

**Issue by Nireya** [GoldSaucerServer/bugtracker#100]
**_I have:_**

- [x] searched existing issues (https://github.com/GoldSaucerServer/bugtracker/issues) to see if the issue has already been opened.
- [x] downloaded and am using Gold Saucer's custom .dat files.
- [x] provided my client version in the space provided below (type /ver into your in-game chat).

**Version**: 30200731_2

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

Did not have any auto-regen when I fought this NM. Wiki states that it has a high auto-regen, along with the below testimonial.

https://ffxiclopedia.fandom.com/wiki/Talk:Megalobugard
"Testimonials
Rediculously easy solo, 75SAM/NIN started fight with 430hp because I had been farming, ended with 430hp. no 2hr needed, started fight with 130~tp, waited until sekkanoki +200tp was ready, fusion skillchain, 2 more single ws's killed it, did notice it has high auto-regen, 1%hp per tick, but no matter,"

**Comment by tankfest** [comment]
Confirmed and fixed, added soon:

https://github.com/project-topaz/topaz/pull/1029
