### ISSUE TITLE
Quest - Scholar Unlock a little Knowledge bug with blue mage 1 hour

### ISSUE THREAD

**Issue by GS-Eren** [GoldSaucerServer/bugtracker#102]
**_I have:_**

- [x] searched existing issues (https://github.com/GoldSaucerServer/bugtracker/issues) to see if the issue has already been opened.
- [x] downloaded and am using Gold Saucer's custom .dat files.
- [x] provided my client version in the space provided below (type /ver into your in-game chat).

**Version**: 

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

Blue mage one hour doesn't work for the part where you have to use one hour and talk to npc.

**Comment by tankfest** [comment]
Issue confirmed, identified, and fixed.  Available after topaz release merges it.

https://github.com/project-topaz/topaz/pull/1024
