### ISSUE TITLE
Crafting - Guild points bug for WW

### ISSUE THREAD

**Issue by GS-Eren** [GoldSaucerServer/bugtracker#103]
**_I have:_**

- [x] searched existing issues (https://github.com/GoldSaucerServer/bugtracker/issues) to see if the issue has already been opened.
- [x] downloaded and am using Gold Saucer's custom .dat files.
- [x] provided my client version in the space provided below (type /ver into your in-game chat).

**Version**: 

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

Item of the day was Mahogany Staff which was worth 2310 guild points The HQ verison Heavy Staff gave the same points 2310 which should be higher than NQ.

**Comment by tankfest** [comment]
https://ffxiclopedia.fandom.com/wiki/Heavy_Staff and https://www.bg-wiki.com/bg/Heavy_Staff both report that the HQ gives 2310, so if this indeed does give more than the NQ, it would need verification from retail.

**Comment by Nireya** [comment]
https://www.ffxiah.com/item/17092/mahogany-staff
"Guild Point value for HQ is same as NQ: 2,310"

A lot of crafting items have the same values for NQ/HQ.
