### ISSUE TITLE
Digs no longer show count

### ISSUE THREAD

**Issue by GS-Eren** [GoldSaucerServer/bugtracker#105]
**_I have:_**

- [x] searched existing issues (https://github.com/GoldSaucerServer/bugtracker/issues) to see if the issue has already been opened.
- [x] downloaded and am using Gold Saucer's custom .dat files.
- [x] provided my client version in the space provided below (type /ver into your in-game chat).

**Version**: 

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

When you dig now it doesn't show how many digs you have left or anything.

**Comment by tankfest** [comment]
Fixed.
