### ISSUE TITLE
Craft - WW guild point of the day bug

### ISSUE THREAD

**Issue by GS-Eren** [GoldSaucerServer/bugtracker#106]
**_I have:_**

- [x] searched existing issues (https://github.com/GoldSaucerServer/bugtracker/issues) to see if the issue has already been opened.
- [x] downloaded and am using Gold Saucer's custom .dat files.
- [x] provided my client version in the space provided below (type /ver into your in-game chat).

**Version**: 

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

npc is asking for obelisk lance which according to wiki it got changed to Armoire 

https://ffxiclopedia.fandom.com/wiki/Obelisk_Lance

**Comment by Nireya** [comment]
Fix and PR'd to Topaz.
