### ISSUE TITLE
NM - Serket bug

### ISSUE THREAD

**Issue by GS-Eren** [GoldSaucerServer/bugtracker#115]
**_I have:_**

- [x] searched existing issues (https://github.com/GoldSaucerServer/bugtracker/issues) to see if the issue has already been opened.
- [x] downloaded and am using Gold Saucer's custom .dat files.
- [x] provided my client version in the space provided below (type /ver into your in-game chat).

**Version**: 

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

Serket Enraged at 20 mins   Its suppose to at 30 mins 

https://ffxiclopedia.fandom.com/wiki/Serket

Does not "Gradually" rage. Rages in 30 minutes.

**Comment by tankfest** [comment]
Verified and fix submitted to topaz:
https://github.com/project-topaz/topaz/pull/1068

It will be pulled into GS soon enough.
