### ISSUE TITLE
Field gear doesn't function at all

### ISSUE THREAD

**Issue by Nireya** [GoldSaucerServer/bugtracker#116]
**_I have:_**

- [x] searched existing issues (https://github.com/GoldSaucerServer/bugtracker/issues) to see if the issue has already been opened.
- [x] downloaded and am using Gold Saucer's custom .dat files.
- [x] provided my client version in the space provided below (type /ver into your in-game chat).

**Version**: 30200731_2

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

Field gear currently doesn't do anything regarding any HELM activities.

**Comment by tankfest** [comment]
Research revealed that the field/workers gear functions as intended, and have now been reworked a touch for our next maintenance.
