### ISSUE TITLE
Promyvions - Spire of Dem boss doesn't use Fissure (add spawns)

### ISSUE THREAD

**Issue by Nireya** [GoldSaucerServer/bugtracker#118]
**_I have:_**

- [x] searched existing issues (https://github.com/GoldSaucerServer/bugtracker/issues) to see if the issue has already been opened.
- [x] downloaded and am using Gold Saucer's custom .dat files.
- [x] provided my client version in the space provided below (type /ver into your in-game chat).

**Version**: 30200731_2

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

The NM doesn't spawn adds or use the ability at all as it should. If I had to guess it uses the ability as a sort of 2h ability in a way, will look for more evidence/info on this and edit later.

**Comment by tankfest** [comment]
I talked to peeps on topaz about this, teo did extensive testing or has extensive knowledge of it... it just fires randomly and usually at <25% hp

**Comment by tankfest** [comment]
I should add that that's exactly how it currently is coded... just a chance for him to use it right now.
