### ISSUE TITLE
Mob - High lvl crawlers rolanberry (S)

### ISSUE THREAD

**Issue by GS-Eren** [GoldSaucerServer/bugtracker#119]
**_I have:_**

- [x] searched existing issues (https://github.com/GoldSaucerServer/bugtracker/issues) to see if the issue has already been opened.
- [x] downloaded and am using Gold Saucer's custom .dat files.
- [x] provided my client version in the space provided below (type /ver into your in-game chat).

**Version**: 

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

Rolanberry Fields (S) Champion Crawlers 93-94 F-8  & F-9

**Comment by tankfest** [comment]
Fixed for next maintenance.  They will now be merit party appropriate at level 82-83.  Thanks!
