### ISSUE TITLE
RNG - Double Shot does not work

### ISSUE THREAD

**Issue by Nireya** [GoldSaucerServer/bugtracker#19]
**_I have:_**

- [x] searched existing issues (https://github.com/GoldSaucerServer/bugtracker/issues) to see if the issue has already been opened.
- [x] downloaded and am using Gold Saucer's custom .dat files.
- [x] provided my client version in the space provided below (type /ver into your in-game chat).

**Version**: 30200604_0

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

The Ranger job ability Double Shot, does not currently function at all.

https://ffxiclopedia.fandom.com/wiki/Double_Shot

**Comment by tankfest** [comment]
Ability removed.  Out of era and seems very powerful.
