### ISSUE TITLE
Missing recipe - Desynthesis of Raptor Strap

### ISSUE THREAD

**Issue by Nireya** [GoldSaucerServer/bugtracker#31]
**_I have:_**

- [x] searched existing issues (https://github.com/GoldSaucerServer/bugtracker/issues) to see if the issue has already been opened.
- [x] downloaded and am using Gold Saucer's custom .dat files.
- [x] provided my client version in the space provided below (type /ver into your in-game chat).

**Version**: 30200604_0

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

The raptor strap desynthesis recipe does not currently work.

https://ffxiclopedia.fandom.com/wiki/Raptor_Strap

**Comment by tankfest** [comment]
Verified and fix submitted to topaz. Thanks!
https://github.com/project-topaz/topaz/pull/968
We will get the fix when it is merged into Topaz's release.
