### ISSUE TITLE
Smoke on the Mountain quest is not repeatable

### ISSUE THREAD

**Issue by Nireya** [GoldSaucerServer/bugtracker#37]
**_I have:_**

- [x] searched existing issues (https://github.com/GoldSaucerServer/bugtracker/issues) to see if the issue has already been opened.
- [x] downloaded and am using Gold Saucer's custom .dat files.
- [x] provided my client version in the space provided below (type /ver into your in-game chat).

**Version**: 30200604_0

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

Currently the quest is technically "repeatable" since you can turn in multiple Galkan Sausages freely, however the campfire portion stops functioning once you turn in the quest for the first time. This in turn means you can no longer make more Galkan Sausage after the fact.

https://ffxiclopedia.fandom.com/wiki/Smoke_on_the_Mountain

**Comment by Nireya** [comment]
https://github.com/project-topaz/topaz/blob/bbfb8312721268bea4349d748a16c14cb5ed02c2/scripts/zones/South_Gustaberg/npcs/qm2.lua

I believe that the code currently only checks if you have the quest in your log, which is why it breaks.

**Comment by tankfest** [comment]
> I believe that the code currently only checks if you have the quest in your log, which is why it breaks after turning it in.

Well discovered!  Issue has been fixed and will be forwarded to topaz.
