### ISSUE TITLE
Serpopard Ishtar Crashes server 

### ISSUE THREAD

**Issue by chapel82** [GoldSaucerServer/bugtracker#42]
**_I have:_**

- [X] searched existing issues (https://github.com/GoldSaucerServer/bugtracker/issues) to see if the issue has already been opened.
- [X] downloaded and am using Gold Saucer's custom .dat files.
- [X] provided my client version in the space provided below (type /ver into your in-game chat).

**Version**:  My Ver is 30200702_2

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

Crashed the server twice Smn was with me at the time.

**Comment by tankfest** [comment]
Issue identified and fixed.  This was due to a recent patch from topaz that fixed TP being improperly removed when a bard swapped instruments.
