### ISSUE TITLE
Cannot Progress ZM8 Return to Delk.

### ISSUE THREAD

**Issue by wickedwitt** [GoldSaucerServer/bugtracker#43]
**_I have:_**

- [X] searched existing issues (https://github.com/GoldSaucerServer/bugtracker/issues) to see if the issue has already been opened.
- [X] downloaded and am using Gold Saucer's custom .dat files.
- [X] provided my client version in the space provided below (type /ver into your in-game chat).

**Version**: 30200702_2

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

I did the optional dialogue in Lower Juneo. I do not get the CS when entering Stellar Fulc and therefore cannot start the fight. I get nothing when clicking on the door.

**Comment by Nireya** [comment]
You have to zone into Stellar Fulcrum from Delkfutt's tower to receive the CS, not use a homepoint warp. This is the case for most story/mission CSes. Eren did this just a few days ago and confirmed.
