### ISSUE TITLE
Overlord Bakgodek's drop table is incorrect

### ISSUE THREAD

**Issue by Nireya** [GoldSaucerServer/bugtracker#50]
**_I have:_**

- [x] searched existing issues (https://github.com/GoldSaucerServer/bugtracker/issues) to see if the issue has already been opened.
- [x] downloaded and am using Gold Saucer's custom .dat files.
- [x] provided my client version in the space provided below (type /ver into your in-game chat).

**Version**: 30200731_2

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

Highlander Targe and Nightmare Sword are supposed to be pooled together with a 100% drop rate. If one drops, the other does not. I've seen both drop on the same kill here. It should also be noted that before they added Juggernaut to KS99 wyrm, it had a very high drop chance with TH2 (80%+). When they added it to the KSNM, they dropped it down. However the drop rate on base Topaz (7%) seems far too low even for what it is.

This is FFXIDB drop rates POST-nerf
http://www.ffxidb.com/zones/150/overlord-bakgodek

http://www.playonline.com/pcd/update/ff11us/20070308c2bbd1/detail.html
"- The items listed below can now be obtained through different methods.

Cassie Earring/Serket Ring/Juggernaut
*The Juggernaut will still also drop from the usual monster, but at a lower probability."

This old wiki page had it dropping at 100% rate
https://ffxiclopedia.fandom.com/wiki/Overlord_Bakgodek?oldid=86862

Also old post from BGwiki claiming it was 100%
https://www.bluegartr.com/threads/32823-Is-Juggernaut-100-Drop

While I'm not arguing for it to be 100% drop rate since we have the KSNM99, it should still be far higher and not kclub level rarity.

**Comment by tankfest** [comment]
Reported and fixed by Nireya!

https://github.com/project-topaz/topaz/pull/1018
