### ISSUE TITLE
Ore Toss is behaving as multi-hit incorrectly

### ISSUE THREAD

**Issue by Nireya** [GoldSaucerServer/bugtracker#56]
**_I have:_**

- [x] searched existing issues (https://github.com/GoldSaucerServer/bugtracker/issues) to see if the issue has already been opened.
- [x] downloaded and am using Gold Saucer's custom .dat files.
- [x] provided my client version in the space provided below (type /ver into your in-game chat).

**Version**: 30200731_2

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

Ore Toss currently will wipe up to 3 shadows when it is a single-hit TP ability.

![Screenshot_156](https://user-images.githubusercontent.com/17558211/89939501-0c16c000-dbe6-11ea-8c16-5f6223420c2f.png)

https://ffxiclopedia.fandom.com/wiki/Category:Quadav

https://github.com/project-topaz/topaz/blob/27b97b7bf30b8336ca5a0a7b9117ce7eed205f18/scripts/globals/mobskills/ore_toss.lua

    local dmg = MobFinalAdjustments(info.dmg, mob, skill, target, tpz.attackType.RANGED, tpz.damageType.BLUNT, MOBPARAM_3_SHADOW)

Edited to include these videos:

Video reference #1: Za'Dha Adamantking vs WAR/NIN Jan 2007
https://youtu.be/OB6vwNs3new?t=94
It's a bit hard to see, but Za'Dha readies Ore Toss while the Warrior has Utsusemi up and it absorbs just 1 shadow. Given the ~Lv80 NM vs subjob skill level, I am doubtful this is an instance of ninjutsu skill reducing the number of shadows taken.

Video reference #2: Za'Dha Adamantking vs PLD/NIN Feb 2007
https://youtu.be/DYpIuX368IM?t=214
https://youtu.be/DYpIuX368IM?t=231
Again, these old videos make it difficult to see, but Za'Dha readies and executes Ore Toss, taking only one shadow. Earlier in this video it both missed and did approximately 450 damage to the Paladin when he was without shadows (casting Ichi both times).

**Comment by tankfest** [comment]
Verified and fix submitted to topaz. Thanks!

We will get the fix when it is merged into Topaz's release.
