### ISSUE TITLE
Everyone's Rancor dealing too much damage

### ISSUE THREAD

**Issue by Nireya** [GoldSaucerServer/bugtracker#57]
**_I have:_**

- [x] searched existing issues (https://github.com/GoldSaucerServer/bugtracker/issues) to see if the issue has already been opened.
- [x] downloaded and am using Gold Saucer's custom .dat files.
- [x] provided my client version in the space provided below (type /ver into your in-game chat).

**Version**: 30200731_2

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

When doing ZM4 BCNM - The Temple of Uggalepih I was hit for 2750 from Everyone's Rancor and I just reset my tonberry hate prior to the fight. Damage needs to be adjusted.

![Screenshot_157](https://user-images.githubusercontent.com/17558211/90080084-b4f11800-dcd7-11ea-9ca4-0cad8da4a1ee.png)

**Comment by tankfest** [comment]
Unsure what the issue is.  Your specific kill counter for tonberries was at 59, so it wasn't reset properly.  When I tested the tonberry hate reset function, it properly reset my hate.  This can likely be closed unless there's further info on it.

**Comment by Nireya** [comment]
Might've just been that then. Will reopen issue if anymore reports of incorrect Everyone's Rancor damage in future.
