### ISSUE TITLE
Ebony Pudding Flan have spells they shouldn't

### ISSUE THREAD

**Issue by wickedwitt** [GoldSaucerServer/bugtracker#61]
**_I have:_**

- [X] searched existing issues (https://github.com/GoldSaucerServer/bugtracker/issues) to see if the issue has already been opened.
- [X] downloaded and am using Gold Saucer's custom .dat files.
- [X] provided my client version in the space provided below (type /ver into your in-game chat).

**Version**: 

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

Ebony Pudding in Mt. Zhayolm are using Bio III as well as T5 single target spells. They never possessed these spells in era.

**Comment by tankfest** [comment]
Request for more information posted in Capture discord.  Pending further info.

**Comment by tankfest** [comment]
Verified and fix submitted to topaz. Thanks!

We will get the fix when it is merged into Topaz's release.
