### ISSUE TITLE
Melody Earrings providing +evasion, not +evasion skill

### ISSUE THREAD

**Issue by Nireya** [GoldSaucerServer/bugtracker#62]
**_I have:_**

- [x] searched existing issues (https://github.com/GoldSaucerServer/bugtracker/issues) to see if the issue has already been opened.
- [x] downloaded and am using Gold Saucer's custom .dat files.
- [x] provided my client version in the space provided below (type /ver into your in-game chat).

**Version**: 30200731_2

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

Wiki makes it clear that this should provide evasion skill rather than flat evasion. I'm sure there's more items out there like this we could add to this bug report later.

https://ffxiclopedia.fandom.com/wiki/Melody_Earring

https://github.com/project-topaz/topaz/blob/ab9936cda85c705e25d24a0069616702bef4f386/sql/item_latents.sql

Currently it reads:

```
-- Melody Earring

INSERT INTO item_latents VALUES(14725, 68, 5, 25, 0); -- EVA+5 song/roll active

-- Melody Earring +1

INSERT INTO item_latents VALUES(14726, 68, 6, 25, 0); -- EVA+6 song/roll active

```

Should instead be:

```
-- Melody Earring

INSERT INTO item_latents VALUES(14725, 108, 5, 25, 0); -- EVA+5 song/roll active

-- Melody Earring +1

INSERT INTO item_latents VALUES(14726, 108, 6, 25, 0); -- EVA+6 song/roll active
```

**Comment by tankfest** [comment]
Verified and fix submitted to topaz.  Thanks!

We will get the fix when it is merged into Topaz's release.
