### ISSUE TITLE
Pahh The Gullcaller incorrect drop rate on Calamar

### ISSUE THREAD

**Issue by Nireya** [GoldSaucerServer/bugtracker#64]
**_I have:_**

- [x] searched existing issues (https://github.com/GoldSaucerServer/bugtracker/issues) to see if the issue has already been opened.
- [x] downloaded and am using Gold Saucer's custom .dat files.
- [x] provided my client version in the space provided below (type /ver into your in-game chat).

**Version**: 30200731_2

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

Drop rate is currently listed at 10% on Topaz:
`INSERT INTO mob_droplist VALUES (1973,0,0,1000,16882,100);`

However on ffxidb it is listed at 52% average, and I also know Catrim is 0/7 on this already.

http://www.ffxidb.com/zones/176/pahh-the-gullcaller

**Comment by tankfest** [comment]
Verified and fix submitted to topaz. Thanks!

We will get the fix when it is merged into Topaz's release.
