### ISSUE TITLE
Spells that have 20.4 cast range should have 21.5 cast range

### ISSUE THREAD

**Issue by Nireya** [GoldSaucerServer/bugtracker#65]
**_I have:_**

- [x] searched existing issues (https://github.com/GoldSaucerServer/bugtracker/issues) to see if the issue has already been opened.
- [x] downloaded and am using Gold Saucer's custom .dat files.
- [x] provided my client version in the space provided below (type /ver into your in-game chat).

**Version**: 30200731_2

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

This recent retail video here shows that spells indeed cast at 21.5 yalms on retail:

https://www.youtube.com/watch?v=XHVqo2tSqzA&feature=youtu.be

On Gold Saucer it is just slightly too short however it has such a huge impact since many AoEs (Mijin Gakure, Astral Flow, etc.) are exactly 20 yalms so it makes it way more difficult to play around those AoEs as a mage for your party or alliance. Topaz database has these spells at 20.4 cast range. 

Potential fix thanks to Caelic:
`UPDATE topazdb.spell_list SET spell_range = 215 WHERE spell_range = 204;
`

**Comment by tankfest** [comment]
Verified and fix submitted to topaz. Thanks!

We will get the fix when it is merged into Topaz's release.
