### ISSUE TITLE
RNG - Dead Aim Trait Missing

### ISSUE THREAD

**Issue by GS-Eren** [GoldSaucerServer/bugtracker#71]
**_I have:_**

- [x] searched existing issues (https://github.com/GoldSaucerServer/bugtracker/issues) to see if the issue has already been opened.
- [x] downloaded and am using Gold Saucer's custom .dat files.
- [x] provided my client version in the space provided below (type /ver into your in-game chat).

**Version**: 

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

Ranger is suppose to get Dead Aim trait starting at level 50.
Game Description: Improves power of critical hits for ranged attacks.

Dead Aim
Obtained: Ranger Level 50
Critical hit Damage: 10%
Dead Aim II
Obtained: Ranger Level 60
Critical hit Damage: 20%
Dead Aim III
Obtained: Ranger Level 70
Critical hit Damage: 30%

**Comment by tankfest** [comment]
Verified and fix submitted to topaz. Thanks!

https://github.com/project-topaz/topaz/pull/966

We will get the fix when it is merged into Topaz's release.
