### ISSUE TITLE
Hurricane Wyvern - not enough spawns

### ISSUE THREAD

**Issue by GS-Eren** [GoldSaucerServer/bugtracker#73]
**_I have:_**

- [x] searched existing issues (https://github.com/GoldSaucerServer/bugtracker/issues) to see if the issue has already been opened.
- [x] downloaded and am using Gold Saucer's custom .dat files.
- [x] provided my client version in the space provided below (type /ver into your in-game chat).

**Version**: 

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

According to wiki and xidb there should be 5 spawns on map 8 (G-9) but there is only one.

**Comment by Nireya** [comment]
Whoever updated the wiki was wrong and they reversed the numbers. Old wiki history has it correct. There was the correct amount of spawns when I farmed there the other day exactly as this wiki article describes.

https://ffxiclopedia.fandom.com/wiki/Hurricane_Wyvern?oldid=833556
