### ISSUE TITLE
Sky - Bartholemew's Knife not obtainable

### ISSUE THREAD

**Issue by Nireya** [GoldSaucerServer/bugtracker#75]
**_I have:_**

- [x] searched existing issues (https://github.com/GoldSaucerServer/bugtracker/issues) to see if the issue has already been opened.
- [x] downloaded and am using Gold Saucer's custom .dat files.
- [x] provided my client version in the space provided below (type /ver into your in-game chat).

**Version**: 30200731_2

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

The mini quest to obtain Bartholomew's Knife does not function.

https://ffxiclopedia.fandom.com/wiki/Bartholomew's_Knife

**Comment by tankfest** [comment]
https://github.com/project-topaz/topaz/issues/978

**Comment by tankfest** [comment]
Implemented: https://github.com/project-topaz/topaz/pull/980
