### ISSUE TITLE
Sky - Mother Globe - Adds/Pets "Slave Globe" give EXP

### ISSUE THREAD

**Issue by Nireya** [GoldSaucerServer/bugtracker#77]
**_I have:_**

- [x] searched existing issues (https://github.com/GoldSaucerServer/bugtracker/issues) to see if the issue has already been opened.
- [x] downloaded and am using Gold Saucer's custom .dat files.
- [x] provided my client version in the space provided below (type /ver into your in-game chat).

**Version**: 30200731_2

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

Mother Globe's pets, "Slave Globe" currently give EXP when they shouldn't.

**Comment by tankfest** [comment]
Verified and fix submitted to topaz. Thanks!

https://github.com/project-topaz/topaz/pull/974

We will get the fix when it is merged into Topaz's release.
