### ISSUE TITLE
SMN - Avatar cast and recast times using 2018 values

### ISSUE THREAD

**Issue by Nireya** [GoldSaucerServer/bugtracker#79]
**_I have:_**

- [x] searched existing issues (https://github.com/GoldSaucerServer/bugtracker/issues) to see if the issue has already been opened.
- [x] downloaded and am using Gold Saucer's custom .dat files.
- [x] provided my client version in the space provided below (type /ver into your in-game chat).

**Version**: 30200731_2

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

Avatars have 5 second cast and 5 second recast currently, and these are the values from a 2018ish update. This should be 7 second cast and 30 second recast or somewhat higher at least to help curb out some of SMN's power. Although I think the cast time should stay as that's a QoL thing.

https://ffxiclopedia.fandom.com/wiki/Carbuncle?oldid=903030
https://ffxiclopedia.fandom.com/wiki/Diabolos?oldid=883611
https://ffxiclopedia.fandom.com/wiki/Fenrir?oldid=884798
https://ffxiclopedia.fandom.com/wiki/Garuda?oldid=910098
https://ffxiclopedia.fandom.com/wiki/Ifrit?oldid=901338
https://ffxiclopedia.fandom.com/wiki/Leviathan?oldid=909431
https://ffxiclopedia.fandom.com/wiki/Ramuh?oldid=904637
https://ffxiclopedia.fandom.com/wiki/Shiva?oldid=910826
https://ffxiclopedia.fandom.com/wiki/Titan?oldid=910058

**Comment by tankfest** [comment]
I disagree about that being a QoL thing, increasing their cast time to 7 seconds will actually make some summoner content as difficult as it was intended to be.

Thanks for bringing this up!
