### ISSUE TITLE
Weather - Elemental spawns missing in several zones

### ISSUE THREAD

**Issue by Nireya** [GoldSaucerServer/bugtracker#81]
**_I have:_**

- [x] searched existing issues (https://github.com/GoldSaucerServer/bugtracker/issues) to see if the issue has already been opened.
- [x] downloaded and am using Gold Saucer's custom .dat files.
- [x] provided my client version in the space provided below (type /ver into your in-game chat).

**Version**: 30200731_2

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

Several zones are completely missing elemental spawns during their appropriate weather.

As of right now confirmed:
- Jugner Forest (possibly only lightning elementals)
- Yhoator Jungle (possibly only fire elementals)
- Yuhtunga Jungle (possibly only fire elementals)

Please comment if you find additional zones or notify me and I will add to this list.

**Comment by tankfest** [comment]
Retail captures received for Jugner and Yuhtunga.  Still need research done on Yhoator.

PR open on topaz for what Nyu captured: https://github.com/project-topaz/topaz/pull/976

Feel free to open a new issue with just yhoator's elementals not spawning.
