### ISSUE TITLE
Aggrod and killed by passive mob- Wamoura Prince

### ISSUE THREAD

**Issue by wickedwitt** [GoldSaucerServer/bugtracker#84]
**_I have:_**

- [X] searched existing issues (https://github.com/GoldSaucerServer/bugtracker/issues) to see if the issue has already been opened.
- [X] downloaded and am using Gold Saucer's custom .dat files.
- [X] provided my client version in the space provided below (type /ver into your in-game chat).

**Version**: 

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

Ran by Wamoura Princes in Mt Z and was promptly dead. These mobs do not aggro. The Wamoura, what they develop into are aggressive, but not Princes. Have yet to see Wamoura on server, so aggro was likely from PH. They either need to transform or not aggro since indistinguishable from other mobs.

**Comment by tankfest** [comment]
Verified and fix submitted to topaz. Thanks!

https://github.com/project-topaz/topaz/pull/977

We will get the fix when it is merged into Topaz's release.
