### ISSUE TITLE
Blue Ribbon Blues Quest Bugged

### ISSUE THREAD

**Issue by rbrashear12** [GoldSaucerServer/bugtracker#92]
**_I have:_**

- [x] searched existing issues (https://github.com/GoldSaucerServer/bugtracker/issues) to see if the issue has already been opened.
- [x] downloaded and am using Gold Saucer's custom .dat files.
- [x] provided my client version in the space provided below (type /ver into your in-game chat).

**Version**: 30200731_2

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

Following quest guide at https://ffxiclopedia.fandom.com/wiki/Blue_Ribbon_Blues, after turning in the purple ribbon to npc Kerutoto, zoning, and rezoning, Kerutoto fails to give back the purple ribbon to continue the quest. The npc repeats the previous dialogue from before turning in the purple ribbon of "I enjoy collecting strange or mysterious things. It's part of my job to investigate them."

Talking to npc Roberta to get a new ribbon from npc Roberta results in no dialogue.

The quest is stuck at this point.

**Comment by tankfest** [comment]
I remember this exact issue from someone before... you have to wait like 2 hours maybe

**Comment by tankfest** [comment]
After doing some digging, I found the culprit and it is indeed a timer.  In 2014/15ish the timer was removed, allowing the player to just zone.  Fixed and submitting to Topaz:
https://github.com/project-topaz/topaz/pull/1033
