### ISSUE TITLE
Mobs - TP Issue with monsters using their moves

### ISSUE THREAD

**Issue by GS-Eren** [GoldSaucerServer/bugtracker#94]
**_I have:_**

- [x] searched existing issues (https://github.com/GoldSaucerServer/bugtracker/issues) to see if the issue has already been opened.
- [x] downloaded and am using Gold Saucer's custom .dat files.
- [x] provided my client version in the space provided below (type /ver into your in-game chat).

**Version**: 

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

Monsters seem to always special moves  at 1000 TP no matter what their hp is.

3000 75% - 100% HP
2000 TP 50% - 74% and below
1000 TP 25% - 49% and below

Is suppose to be the right way mobs are suppose to use their special moves.

**Comment by tankfest** [comment]
https://github.com/project-topaz/topaz/issues/1032

**Comment by tankfest** [comment]
Fixed:
https://github.com/project-topaz/topaz/pull/1046
