### ISSUE TITLE
Mob Ability - Dancing Chains - Fomor family - Does (absurd) damage when it should not even deal damage

### ISSUE THREAD

**Issue by Nireya** [GoldSaucerServer/bugtracker#95]
**_I have:_**

- [x] searched existing issues (https://github.com/GoldSaucerServer/bugtracker/issues) to see if the issue has already been opened.
- [x] downloaded and am using Gold Saucer's custom .dat files.
- [x] provided my client version in the space provided below (type /ver into your in-game chat).

**Version**: 30200731_2

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

This Mob TP should only be inflicting a 15-tick 10y' AoE drown, but has plagued private servers for long time by doing ridiculous AoE damage coupled with that powerful DoT making /NIN mandatory for every job during CoP missions. Would love for it to be corrected.

https://ffxiclopedia.fandom.com/wiki/Category:Fomors
https://www.bg-wiki.com/bg/Category:Fomor

![img_20200826_203219](https://user-images.githubusercontent.com/17558211/91375756-800db680-e7e9-11ea-8329-2d0f82480205.jpg)

**Comment by tankfest** [comment]
Verified and fixed:
https://github.com/project-topaz/topaz/pull/1012
