### ISSUE TITLE
Mob Ability - Blood Drain - Giant Bat family - Goes through Utsusemi when it should not

### ISSUE THREAD

**Issue by Nireya** [GoldSaucerServer/bugtracker#96]
**_I have:_**

- [x] searched existing issues (https://github.com/GoldSaucerServer/bugtracker/issues) to see if the issue has already been opened.
- [x] downloaded and am using Gold Saucer's custom .dat files.
- [x] provided my client version in the space provided below (type /ver into your in-game chat).

**Version**: 30200731_2

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

This mob ability currently goes through Utsusemi when it should not. 

Found on this NM's wiki page in the description as evidence:
https://ffxiclopedia.fandom.com/wiki/Asanbosam

"Blood Drain: Modified version that ignores Utsusemi. Single target Drain." 
Implies that only this NM's Blood Drain ignores Utsusemi, whereas that is normally not the case. 
"

**Comment by tankfest** [comment]
Verified and fixed:

https://github.com/project-topaz/topaz/pull/1031
